version: "3.3"
services:
    latex:        
        image: ghcr.io/khlam/latexmk/latexmk:latest

        volumes:
          - ./doc/:/app/
        
        command: bash -c "latexmk -pvc -pdf -view=none main.tex"